version: '3.11'


services:


  redis:
    image: redis:alpine
    env_file:
      - ./.env
    restart: on-failure

  db:
    image: postgres:15-alpine
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}


    restart: on-failure
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command:
       sh -c "alembic upgrade head && python main.py"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
      - redis


volumes:
  pgdata: