"""autoencryment=True, Posts

Revision ID: 5014e4ae9182
Revises: 6dd220a8eb31
Create Date: 2024-01-16 18:06:42.288969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5014e4ae9182'
down_revision: Union[str, None] = '6dd220a8eb31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
