"""Added name field

Revision ID: 7db9bbdfd2d1
Revises: 33b581594c5b
Create Date: 2024-01-11 20:16:05.680579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db9bbdfd2d1'
down_revision: Union[str, None] = '33b581594c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'name')
    # ### end Alembic commands ###
