"""AdditionalPost, ContactMe tables

Revision ID: b2af1c77806c
Revises: 7db9bbdfd2d1
Create Date: 2024-01-13 14:39:43.232122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2af1c77806c'
down_revision: Union[str, None] = '7db9bbdfd2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_additional_posts_id'), 'additional_posts', ['id'], unique=False)
    op.create_table('contact_me',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_me_id'), 'contact_me', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_me_id'), table_name='contact_me')
    op.drop_table('contact_me')
    op.drop_index(op.f('ix_additional_posts_id'), table_name='additional_posts')
    op.drop_table('additional_posts')
    # ### end Alembic commands ###
