"""added file_type: str 

Revision ID: d887c0f3d79f
Revises: 5014e4ae9182
Create Date: 2024-01-16 20:13:40.608361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd887c0f3d79f'
down_revision: Union[str, None] = '5014e4ae9182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('additional_posts', sa.Column('file_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('additional_posts', 'file_type')
    # ### end Alembic commands ###
